/**
 * `domain` alimenta a resolução de ícone via serviço de logo por domínio
 * (ver docs/02-modelagem-dados.md § Estratégia de ícones). Confirmar/ajustar
 * os domínios antes de rodar o seed em produção.
 */
export const SEEDED_INSTITUTIONS = [
  { name: "Banco do Brasil", domain: "bb.com.br" },
  { name: "Banco do Nordeste", domain: "bnb.gov.br" },
  { name: "Banco Mercantil do Brasil", domain: "mercantildobrasil.com.br" },
  { name: "Banrisul", domain: "banrisul.com.br" },
  { name: "BMG", domain: "bancobmg.com.br" },
  { name: "Bradesco", domain: "bradesco.com.br" },
  { name: "BRB", domain: "brb.com.br" },
  { name: "BTG Pactual", domain: "btgpactual.com" },
  { name: "BS2", domain: "bs2.com" },
  { name: "BV", domain: "bv.com.br" },
  { name: "C6 Bank", domain: "c6bank.com.br" },
  { name: "Caixa", domain: "caixa.gov.br" },
  { name: "Citibank", domain: "citibank.com.br" },
  { name: "Clear", domain: "clear.com.br" },
  { name: "Cora", domain: "cora.com.br" },
  { name: "Daycoval", domain: "daycoval.com.br" },
  { name: "Digio", domain: "digio.com.br" },
  { name: "HSBC", domain: "hsbc.com.br" },
  { name: "Inter", domain: "bancointer.com.br" },
  { name: "Itaú", domain: "itau.com.br" },
  { name: "Mercado Pago", domain: "mercadopago.com.br" },
  { name: "Modal", domain: "modalmais.com.br" },
  { name: "Neon", domain: "neon.com.br" },
  { name: "Next", domain: "next.me" },
  { name: "Nomad", domain: "nomadglobal.com" },
  { name: "Nubank", domain: "nubank.com.br" },
  { name: "Original", domain: "original.com.br" },
  { name: "PagBank", domain: "pagbank.com.br" },
  { name: "Pan", domain: "bancopan.com.br" },
  { name: "PicPay", domain: "picpay.com" },
  { name: "Rico", domain: "rico.com.vc" },
  { name: "Safra", domain: "safra.com.br" },
  { name: "Santander", domain: "santander.com.br" },
  { name: "Sicoob", domain: "sicoob.com.br" },
  { name: "Sicredi", domain: "sicredi.com.br" },
  { name: "Stone", domain: "stone.com.br" },
  { name: "Votorantim", domain: "bancovotorantim.com.br" },
  { name: "Warren", domain: "warren.com.br" },
  { name: "XP Investimentos", domain: "xpi.com.br" },
] as const;
